### ISSUE TITLE
Getting conflict after the login

### ISSUE THREAD

**Issue by guyng** [Terbau/fortnitepy#141]
I'm getting a Conflict 409 status code response from the epiclogin method. 
It was working all fine for the last few month but this error started from 2 days ago.
Anyone else had it? is there a solution for it? my account email/password did not change

**Comment by guyng** [comment]
@Terbau

**Comment by Terbau** [comment]
Seems like epic decided to reset all device auths for bots. You can generate a new one by doing the following:
1. Navigate to your device_auths.json (considering thats the method for storing auths you are using)
2. Delete the entry matching the email of the account you want to generate a new device auth for.
3. Start your fortnitepy application and follow the steps.

Alternatively you could just rename your current device_auths.json file so that a new one is generated upon start. This way you don't have to look for specific device auths to delete.

**Comment by Terbau** [comment]
I'll leave this issue open for a couple of days so that others can easily find it.

**Comment by guyng** [comment]
> Seems like epic decided to reset all device auths for bots. You can generate a new one by doing the following:
> 
> 1. Navigate to your device_auths.json (considering thats the method for storing auths you are using)
> 2. Delete the entry matching the email of the account you want to generate a new device auth for.
> 3. Start your fortnitepy application and follow the steps.
> 
> Alternatively you could just rename your current device_auths.json file so that a new one is generated upon start. This way you don't have to look for specific device auths to delete.

I did it but before the exchange code step, when i do the login method i get a 409 response of conflicted(using the device auth method). Usually after the login get request i'd get status of 200 and then the exchange code would be generated but since few days ago it can't even generate an exchange code and the login method returns 409.
I also checked with multiple epic accounts same results, and tried also from different ip's.
Any ideas?

**Comment by guyng** [comment]
Also, Is it just me, or it happens to you too? wanna make sure the problem isn't just on my end

**Comment by guyng** [comment]
@Terbau any news?
