### ISSUE TITLE
Captcha was enforced. Please enter a valid authorization code

### ISSUE THREAD

**Issue by johnabil** [Terbau/fortnitepy#142]
This message come to me when I try the basic usage example and I can't get the authorization code also event_device_auth_generate does not work

python version 3.9

**Comment by Terbau** [comment]
If `event_device_auth_generate` is not fired after entering a new authorization code, its most likely because you have changed something as all the examples still work. However, if you are talking about generating a new device auth (probably because epic recently disabled all existing device auths), then you can achieve this by setting `prompt_code_if_invalid=True` in [AdvancedAuth](https://fortnitepy.readthedocs.io/en/latest/api.html#fortnitepy.AdvancedAuth).

If you have any more questions related to authentication, I recommend joining the support server.
