### ISSUE TITLE
PartyError: Incompatible net_cl

### ISSUE THREAD

**Issue by lukas819** [Terbau/fortnitepy#15]
When i inviting the "bot" then is coming a error example: "Task exception was never retrieved
future: <Task finished coro=<XMPPClient.process_event_message() done, defined at C:\Users\******\Desktop\fortnitepy-master\fortnitepy\xmpp.py:88> exception=PartyError('Incompatible net_cl')>
Traceback (most recent call last):
  File "C:\Users\******\Desktop\fortnitepy-master\fortnitepy\xmpp.py", line 185, in process_event_message
    raise PartyError('Incompatible net_cl')
fortnitepy.errors.PartyError: Incompatible net_cl"

**Comment by Terbau** [comment]
When fortnite releases a new content update they also update a specific number named netcl needed for the party service to work. When updating this lib I also update the net_cl to match the new one. However, since fortnite seems to update their game every week I sometimes don't keep up and you have to find and initialize the client with the correct one yourself.

**Guide to find netcl.**
1. Navigate to the folder where you find your fortnite logs. Usually something like this: `C:\Users\%your_user%\AppData\Local\FortniteGame\Saved\Logs`.
2. Go into the latest log file (Typically named `FortniteGame`).
3. Press ctrl + f and do a search for `netcl`. You should then find a seven digit number.

**This is how you launch the client with the manual netcl:**
```py
# pass the netcl to with the net_cl keyword when initializing the client.
client = fortnitepy.Client(
    email='email',
    password='password',
    net_cl='7605985'
)
```
